alloy:
  configMap:
    content: |
      otelcol.receiver.otlp "default" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }
        http {
          endpoint = "0.0.0.0:4318"
        }
        output {
          traces  = [
            otelcol.exporter.otlp.tempo.input,
            otelcol.connector.spanmetrics.default.input
          ]
        }
      }

      otelcol.connector.spanmetrics "default" {
        dimension { name = "http.method" }
        dimension { name = "http.status_code" }
        
        output {
          metrics = [otelcol.exporter.prometheus.default.input]
        }
      }

      otelcol.exporter.prometheus "default" {
        forward_to = [prometheus.remote_write.default.receiver]
      }

      prometheus.remote_write "default" {
        endpoint {
          url = "http://my-monitoring-kube-prometh-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
        }
      }

      otelcol.exporter.otlp "tempo" {
        client {
          endpoint = "tempo:4317"
          tls {
            insecure = true
          }
        }
      }