apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deploy-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "services", "deployments", "replicasets", 
              "secrets", "configmaps", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# dev
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-rolebinding
  namespace: bookinfo-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-deploy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins
---
# uat
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-rolebinding
  namespace: bookinfo-uat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-deploy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins
---
# prd
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-rolebinding
  namespace: bookinfo-prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-deploy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins